# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: capistrano2-zabbix 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "capistrano2-zabbix".freeze
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Marek Skrobacki".freeze]
  s.date = "2022-08-24"
  s.description = "\n  Tired of manually creating maintenance objects in your Zabbix monitoring\n  system for every new release of your application ? This gem is for you! It\n  automates creation and removal of necessary objects so that your code can be\n  released without unnecessary false alerts.\n  ".freeze
  s.email = "skrobul@skrobul.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".github/workflows/ruby.yml",
    ".rspec",
    ".rubocop.yml",
    ".ruby-version",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "capistrano2-zabbix.gemspec",
    "lib/capistrano/tasks.rb",
    "lib/capistrano2-zabbix.rb",
    "lib/zabbix_maintenance.rb",
    "spec/capistrano2-zabbix_spec.rb",
    "spec/cassettes/ZabbixMaintenance/_authenticated_/when_authenticated/.yml",
    "spec/cassettes/ZabbixMaintenance/_authenticated_/when_not_authenticated/returns_false.yml",
    "spec/cassettes/ZabbixMaintenance/_create/with_valid_parameters/creates_maintenance_period_with_correct_groupid.yml",
    "spec/cassettes/ZabbixMaintenance/_delete/removes_the_maintenance.yml",
    "spec/cassettes/ZabbixMaintenance/_exists_/when_maintenance_does_not_exist_on_remote_server/.yml",
    "spec/cassettes/ZabbixMaintenance/_exists_/when_maintenance_exists_on_remote_server/.yml",
    "spec/cassettes/ZabbixMaintenance/_maint_id/when_maintenance_exsts/returns_correct_ID.yml",
    "spec/cassettes/ZabbixMaintenance/_new/authenticates_with_correct_credentials.yml",
    "spec/cassettes/ZabbixMaintenance/_new/password_is_incorrect/raises_an_exception.yml",
    "spec/spec_helper.rb",
    "spec/zabbix_maintenance_spec.rb"
  ]
  s.homepage = "http://github.com/skrobul/capistrano2-zabbix".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.3.7".freeze
  s.summary = "Create maintenances in Zabbix through Capistrano deployment".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<zabbixapi>.freeze, ["~> 4.2.0"])
    s.add_runtime_dependency(%q<capistrano>.freeze, ["~> 2.0"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.2"])
    s.add_development_dependency(%q<yard>.freeze, ["~> 0.7"])
    s.add_development_dependency(%q<rdoc>.freeze, [">= 4.3.0"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.10"])
    s.add_development_dependency(%q<vcr>.freeze, ["~> 2.9"])
    s.add_development_dependency(%q<webmock>.freeze, ["~> 1.21"])
    s.add_development_dependency(%q<crack>.freeze, ["~> 0.3.2"])
    s.add_development_dependency(%q<pry>.freeze, [">= 0.10"])
    s.add_development_dependency(%q<guard-rubocop>.freeze, ["~> 1.2"])
    s.add_development_dependency(%q<guard>.freeze, ["~> 2.12"])
    s.add_development_dependency(%q<guard-rspec>.freeze, ["~> 4.5"])
  else
    s.add_dependency(%q<zabbixapi>.freeze, ["~> 4.2.0"])
    s.add_dependency(%q<capistrano>.freeze, ["~> 2.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.2"])
    s.add_dependency(%q<yard>.freeze, ["~> 0.7"])
    s.add_dependency(%q<rdoc>.freeze, [">= 4.3.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.10"])
    s.add_dependency(%q<vcr>.freeze, ["~> 2.9"])
    s.add_dependency(%q<webmock>.freeze, ["~> 1.21"])
    s.add_dependency(%q<crack>.freeze, ["~> 0.3.2"])
    s.add_dependency(%q<pry>.freeze, [">= 0.10"])
    s.add_dependency(%q<guard-rubocop>.freeze, ["~> 1.2"])
    s.add_dependency(%q<guard>.freeze, ["~> 2.12"])
    s.add_dependency(%q<guard-rspec>.freeze, ["~> 4.5"])
  end
end

